FROM --platform=linux/amd64 stateadev/myubuntu:latest
# copy and save keystore/truststore
COPY kafka.consumerstats.keystore.jks /home/spring/client-certs/kafka.consumerstats.keystore.jks
COPY kafka.consumerstats.truststore.jks /home/spring/client-certs/kafka.consumerstats.truststore.jks