FROM --platform=linux/amd64 stateadev/myubuntu:latest
# copy and save keystore/truststore
COPY kafka.producerstats.keystore.jks /home/spring/client-certs/kafka.producerstats.keystore.jks
COPY kafka.producerstats.truststore.jks /home/spring/client-certs/kafka.producerstats.truststore.jks