FROM --platform=linux/amd64 stateadev/myubuntu:latest
# copy and save keystore/truststore
COPY kafka.producerforecasts.keystore.jks /home/spring/client-certs/kafka.producerforecasts.keystore.jks
COPY kafka.producerforecasts.truststore.jks /home/spring/client-certs/kafka.producerforecasts.truststore.jks