FROM --platform=linux/amd64 stateadev/myubuntu:latest
# copy and save keystore/truststore
COPY kafka.consumerforecasts.keystore.jks /home/spring/client-certs/kafka.consumerforecasts.keystore.jks
COPY kafka.consumerforecasts.truststore.jks /home/spring/client-certs/kafka.consumerforecasts.truststore.jks