import { faker } from "@faker-js/faker";
import Head from "next/head";
import Link from "next/link";
import BarChart from "../components/BarChart";
import { Footer } from "../components/Footer";
import Navbar from "../components/Navbar";
import { labels } from "../components/BarChart";

export default function Home() {
  return (
    <>
      <Head>
        <title>TouriStats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar page="home" />
      <div className="w-full h-full text-center pt-20">
        <p className="uppercase text-sm tracking-widest text-gray-600 my-10 px-10">
          Dai uno sguardo alle nostre statistiche
        </p>
        <h1 className="uppercase text-gray-800 my-10 px-10">
          Benvenuti in <span className="text-[#284697]">Touri</span>
          <span className="text-[#00ACC1]">Stats</span>
        </h1>
        <p className="tracking-wide text-gray-600 mx-auto max-w-[70%]">
          <span className="text-[#284697] text-xl">Touri</span>
          <span className="text-[#00ACC1] text-xl">Stats </span>è un servizio
          web dedicato all'analisi del flusso turistico in
          <span className="uppercase font-bold"> Sardegna </span>
          <br />
          Basato su dataset ufficiali Istat, forniamo statistiche e previsioni
          sui flussi di turisti italiani e stranieri verso la regione
        </p>
        <div className="text-gray-700">
          <h2 className="mt-10 mb-14 px-10">Statistiche anno corrente</h2>
          <div className="chart">
            <BarChart
              data={{
                labels: labels,
                datasets: [
                  {
                    data: labels.map(() =>
                      faker.datatype.number({ min: 20000, max: 100000 })
                    ),
                    backgroundColor: "#284697",
                  },
                ],
              }}
            />
          </div>
          <button className="mb-10 bg-transparent hover:bg-blue-500 text-blue-700  hover:text-white font-semibold py-2 px-4 border border-blue-500 hover:border-transparent rounded">
            <Link href="/statistiche">Vai a Statistiche</Link>
          </button>
          <h2 className="mt-10 mb-14 px-10">Previsioni anno successivo</h2>
          <div className="chart">
            <BarChart
              data={{
                labels: labels,
                datasets: [
                  {
                    data: labels.map(() =>
                      faker.datatype.number({ min: 20000, max: 100000 })
                    ),
                    backgroundColor: "#00ACC1",
                  },
                ],
              }}
            />
          </div>
          <button className="mb-10 bg-transparent hover:bg-blue-500 text-blue-700 hover:text-white font-semibold py-2 px-4 border border-blue-500 hover:border-transparent rounded">
            <Link href="/previsioni">Vai a Previsioni</Link>
          </button>
        </div>
      </div>
      <Footer />
    </>
  );
}
