import { faker } from "@faker-js/faker";
import Head from "next/head";
import Link from "next/link";
import BarChart from "../components/BarChart";
import Navbar from "../components/Navbar";

export default function Home() {
  const labels = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "June",
    "July",
    "Aug",
    "Sept",
    "Oct",
    "Nov",
    "Dec",
  ];

  return (
    <div>
      <Head>
        <title>TouriStats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar page="home" />
      <div className="w-full h-full flex justify-center pt-20">
        <div className="text-center">
          <p className="uppercase text-sm tracking-widest text-gray-600 mt-10">
            Dai uno sguardo alle nostre statistiche
          </p>
          <h1 className="text-gray-800 uppercase my-10">
            Benvenuti in <span className="text-[#284697]">Touri</span>
            <span className="text-[#00ACC1]">Stats</span>
          </h1>
          <p className="text-gray-600 mx-auto max-w-[70%] tracking-wide ">
            <span className="text-[#284697] text-xl">Touri</span>
            <span className="text-[#00ACC1] text-xl">Stats </span>è un servizio
            web dedicato all'analisi del flusso turistico in{" "}
            <span className="uppercase font-bold"> Sardegna </span>
            <br />
            Basato su dataset ufficiali Istat, forniamo statistiche e previsioni
            sui flussi di turisti italiani e stranieri verso la regione
          </p>
          <div className="text-center text-gray-700">
            <h2 className="my-10">Statistiche anno corrente</h2>
            <div className="w-3/4 mt-16 mb-12 mx-auto">
              <div className="chart">
                <BarChart
                  data={{
                    labels: labels,
                    datasets: [
                      {
                        data: labels.map(() =>
                          faker.datatype.number({ min: 20000, max: 100000 })
                        ),
                        backgroundColor: "#284697",
                      },
                    ],
                  }}
                />
              </div>
            </div>
            <button className="mb-16 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
              <Link href="/statistiche">Vai a Statistiche</Link>
            </button>
            <h2 className="mb-10">Previsioni anno successivo</h2>
            <div className="w-3/4 mt-16 mb-12 mx-auto">
              <div className="chart">
                <BarChart
                  data={{
                    labels: labels,
                    datasets: [
                      {
                        data: labels.map(() =>
                          faker.datatype.number({ min: 20000, max: 100000 })
                        ),
                        backgroundColor: "#00ACC1",
                      },
                    ],
                  }}
                />
              </div>
            </div>
            <button className="mb-10 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
              <Link href="/previsioni">Vai a Previsioni</Link>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
